backend:
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: 5432
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}  # Adicione esta linha para especificar a senha
      database: ${POSTGRES_DB}
