backstage:
  build: .
  ports:
    - "7007:7007"
  environment:
    POSTGRES_HOST: db                  
    POSTGRES_USER: your_username         
    POSTGRES_PASSWORD: 12345
    POSTGRES_DB: your_database          
  depends_on:
    - db
